

create table `countries` (
	`id` int (11),
	`iso` char (6),
	`name` varchar (240),
	`nicename` varchar (240),
	`iso3` char (9),
	`numcode` smallint (6),
	`phonecode` int (5)
); 
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('1','AF','AFGHANISTAN','Afghanistan','AFG','4','93');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('2','AL','ALBANIA','Albania','ALB','8','355');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('3','DZ','ALGERIA','Algeria','DZA','12','213');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('4','AS','AMERICAN SAMOA','American Samoa','ASM','16','1684');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('5','AD','ANDORRA','Andorra','AND','20','376');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('6','AO','ANGOLA','Angola','AGO','24','244');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('7','AI','ANGUILLA','Anguilla','AIA','660','1264');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('8','AQ','ANTARCTICA','Antarctica',NULL,NULL,'0');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('9','AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','28','1268');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('10','AR','ARGENTINA','Argentina','ARG','32','54');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('11','AM','ARMENIA','Armenia','ARM','51','374');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('12','AW','ARUBA','Aruba','ABW','533','297');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('13','AU','AUSTRALIA','Australia','AUS','36','61');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('14','AT','AUSTRIA','Austria','AUT','40','43');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('15','AZ','AZERBAIJAN','Azerbaijan','AZE','31','994');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('16','BS','BAHAMAS','Bahamas','BHS','44','1242');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('17','BH','BAHRAIN','Bahrain','BHR','48','973');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('18','BD','BANGLADESH','Bangladesh','BGD','50','880');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('19','BB','BARBADOS','Barbados','BRB','52','1246');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('20','BY','BELARUS','Belarus','BLR','112','375');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('21','BE','BELGIUM','Belgium','BEL','56','32');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('22','BZ','BELIZE','Belize','BLZ','84','501');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('23','BJ','BENIN','Benin','BEN','204','229');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('24','BM','BERMUDA','Bermuda','BMU','60','1441');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('25','BT','BHUTAN','Bhutan','BTN','64','975');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('26','BO','BOLIVIA','Bolivia','BOL','68','591');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('27','BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','70','387');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('28','BW','BOTSWANA','Botswana','BWA','72','267');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('29','BV','BOUVET ISLAND','Bouvet Island',NULL,NULL,'0');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('30','BR','BRAZIL','Brazil','BRA','76','55');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('31','IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL,'246');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('32','BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','96','673');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('33','BG','BULGARIA','Bulgaria','BGR','100','359');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('34','BF','BURKINA FASO','Burkina Faso','BFA','854','226');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('35','BI','BURUNDI','Burundi','BDI','108','257');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('36','KH','CAMBODIA','Cambodia','KHM','116','855');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('37','CM','CAMEROON','Cameroon','CMR','120','237');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('38','CA','CANADA','Canada','CAN','124','1');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('39','CV','CAPE VERDE','Cape Verde','CPV','132','238');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('40','KY','CAYMAN ISLANDS','Cayman Islands','CYM','136','1345');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('41','CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140','236');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('42','TD','CHAD','Chad','TCD','148','235');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('43','CL','CHILE','Chile','CHL','152','56');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('44','CN','CHINA','China','CHN','156','86');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('45','CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL,'61');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('46','CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL,'672');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('47','CO','COLOMBIA','Colombia','COL','170','57');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('48','KM','COMOROS','Comoros','COM','174','269');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('49','CG','CONGO','Congo','COG','178','242');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('50','CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180','242');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('51','CK','COOK ISLANDS','Cook Islands','COK','184','682');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('52','CR','COSTA RICA','Costa Rica','CRI','188','506');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('53','CI','COTE D\'IVOIRE','Cote D\'Ivoire','CIV','384','225');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('54','HR','CROATIA','Croatia','HRV','191','385');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('55','CU','CUBA','Cuba','CUB','192','53');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('56','CY','CYPRUS','Cyprus','CYP','196','357');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('57','CZ','CZECH REPUBLIC','Czech Republic','CZE','203','420');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('58','DK','DENMARK','Denmark','DNK','208','45');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('59','DJ','DJIBOUTI','Djibouti','DJI','262','253');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('60','DM','DOMINICA','Dominica','DMA','212','1767');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('61','DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214','1809');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('62','EC','ECUADOR','Ecuador','ECU','218','593');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('63','EG','EGYPT','Egypt','EGY','818','20');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('64','SV','EL SALVADOR','El Salvador','SLV','222','503');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('65','GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226','240');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('66','ER','ERITREA','Eritrea','ERI','232','291');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('67','EE','ESTONIA','Estonia','EST','233','372');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('68','ET','ETHIOPIA','Ethiopia','ETH','231','251');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('69','FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK','238','500');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('70','FO','FAROE ISLANDS','Faroe Islands','FRO','234','298');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('71','FJ','FIJI','Fiji','FJI','242','679');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('72','FI','FINLAND','Finland','FIN','246','358');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('73','FR','FRANCE','France','FRA','250','33');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('74','GF','FRENCH GUIANA','French Guiana','GUF','254','594');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('75','PF','FRENCH POLYNESIA','French Polynesia','PYF','258','689');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('76','TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL,'0');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('77','GA','GABON','Gabon','GAB','266','241');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('78','GM','GAMBIA','Gambia','GMB','270','220');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('79','GE','GEORGIA','Georgia','GEO','268','995');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('80','DE','GERMANY','Germany','DEU','276','49');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('81','GH','GHANA','Ghana','GHA','288','233');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('82','GI','GIBRALTAR','Gibraltar','GIB','292','350');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('83','GR','GREECE','Greece','GRC','300','30');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('84','GL','GREENLAND','Greenland','GRL','304','299');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('85','GD','GRENADA','Grenada','GRD','308','1473');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('86','GP','GUADELOUPE','Guadeloupe','GLP','312','590');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('87','GU','GUAM','Guam','GUM','316','1671');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('88','GT','GUATEMALA','Guatemala','GTM','320','502');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('89','GN','GUINEA','Guinea','GIN','324','224');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('90','GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624','245');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('91','GY','GUYANA','Guyana','GUY','328','592');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('92','HT','HAITI','Haiti','HTI','332','509');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('93','HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL,'0');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('94','VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT','336','39');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('95','HN','HONDURAS','Honduras','HND','340','504');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('96','HK','HONG KONG','Hong Kong','HKG','344','852');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('97','HU','HUNGARY','Hungary','HUN','348','36');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('98','IS','ICELAND','Iceland','ISL','352','354');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('99','IN','INDIA','India','IND','356','91');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('100','ID','INDONESIA','Indonesia','IDN','360','62');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('101','IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364','98');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('102','IQ','IRAQ','Iraq','IRQ','368','964');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('103','IE','IRELAND','Ireland','IRL','372','353');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('104','IL','ISRAEL','Israel','ISR','376','972');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('105','IT','ITALY','Italy','ITA','380','39');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('106','JM','JAMAICA','Jamaica','JAM','388','1876');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('107','JP','JAPAN','Japan','JPN','392','81');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('108','JO','JORDAN','Jordan','JOR','400','962');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('109','KZ','KAZAKHSTAN','Kazakhstan','KAZ','398','7');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('110','KE','KENYA','Kenya','KEN','404','254');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('111','KI','KIRIBATI','Kiribati','KIR','296','686');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('112','KP','KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','Korea, Democratic People\'s Republic of','PRK','408','850');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('113','KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410','82');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('114','KW','KUWAIT','Kuwait','KWT','414','965');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('115','KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417','996');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('116','LA','LAO PEOPLE\'S DEMOCRATIC REPUBLIC','Lao People\'s Democratic Republic','LAO','418','856');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('117','LV','LATVIA','Latvia','LVA','428','371');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('118','LB','LEBANON','Lebanon','LBN','422','961');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('119','LS','LESOTHO','Lesotho','LSO','426','266');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('120','LR','LIBERIA','Liberia','LBR','430','231');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('121','LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434','218');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('122','LI','LIECHTENSTEIN','Liechtenstein','LIE','438','423');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('123','LT','LITHUANIA','Lithuania','LTU','440','370');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('124','LU','LUXEMBOURG','Luxembourg','LUX','442','352');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('125','MO','MACAO','Macao','MAC','446','853');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('126','MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807','389');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('127','MG','MADAGASCAR','Madagascar','MDG','450','261');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('128','MW','MALAWI','Malawi','MWI','454','265');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('129','MY','MALAYSIA','Malaysia','MYS','458','60');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('130','MV','MALDIVES','Maldives','MDV','462','960');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('131','ML','MALI','Mali','MLI','466','223');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('132','MT','MALTA','Malta','MLT','470','356');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('133','MH','MARSHALL ISLANDS','Marshall Islands','MHL','584','692');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('134','MQ','MARTINIQUE','Martinique','MTQ','474','596');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('135','MR','MAURITANIA','Mauritania','MRT','478','222');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('136','MU','MAURITIUS','Mauritius','MUS','480','230');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('137','YT','MAYOTTE','Mayotte',NULL,NULL,'269');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('138','MX','MEXICO','Mexico','MEX','484','52');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('139','FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583','691');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('140','MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498','373');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('141','MC','MONACO','Monaco','MCO','492','377');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('142','MN','MONGOLIA','Mongolia','MNG','496','976');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('143','MS','MONTSERRAT','Montserrat','MSR','500','1664');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('144','MA','MOROCCO','Morocco','MAR','504','212');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('145','MZ','MOZAMBIQUE','Mozambique','MOZ','508','258');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('146','MM','MYANMAR','Myanmar','MMR','104','95');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('147','NA','NAMIBIA','Namibia','NAM','516','264');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('148','NR','NAURU','Nauru','NRU','520','674');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('149','NP','NEPAL','Nepal','NPL','524','977');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('150','NL','NETHERLANDS','Netherlands','NLD','528','31');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('151','AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT','530','599');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('152','NC','NEW CALEDONIA','New Caledonia','NCL','540','687');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('153','NZ','NEW ZEALAND','New Zealand','NZL','554','64');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('154','NI','NICARAGUA','Nicaragua','NIC','558','505');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('155','NE','NIGER','Niger','NER','562','227');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('156','NG','NIGERIA','Nigeria','NGA','566','234');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('157','NU','NIUE','Niue','NIU','570','683');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('158','NF','NORFOLK ISLAND','Norfolk Island','NFK','574','672');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('159','MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580','1670');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('160','NO','NORWAY','Norway','NOR','578','47');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('161','OM','OMAN','Oman','OMN','512','968');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('162','PK','PAKISTAN','Pakistan','PAK','586','92');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('163','PW','PALAU','Palau','PLW','585','680');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('164','PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL,'970');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('165','PA','PANAMA','Panama','PAN','591','507');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('166','PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598','675');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('167','PY','PARAGUAY','Paraguay','PRY','600','595');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('168','PE','PERU','Peru','PER','604','51');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('169','PH','PHILIPPINES','Philippines','PHL','608','63');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('170','PN','PITCAIRN','Pitcairn','PCN','612','0');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('171','PL','POLAND','Poland','POL','616','48');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('172','PT','PORTUGAL','Portugal','PRT','620','351');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('173','PR','PUERTO RICO','Puerto Rico','PRI','630','1787');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('174','QA','QATAR','Qatar','QAT','634','974');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('175','RE','REUNION','Reunion','REU','638','262');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('176','RO','ROMANIA','Romania','ROM','642','40');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('177','RU','RUSSIAN FEDERATION','Russian Federation','RUS','643','70');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('178','RW','RWANDA','Rwanda','RWA','646','250');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('179','SH','SAINT HELENA','Saint Helena','SHN','654','290');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('180','KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659','1869');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('181','LC','SAINT LUCIA','Saint Lucia','LCA','662','1758');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('182','PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM','666','508');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('183','VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670','1784');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('184','WS','SAMOA','Samoa','WSM','882','684');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('185','SM','SAN MARINO','San Marino','SMR','674','378');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('186','ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678','239');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('187','SA','SAUDI ARABIA','Saudi Arabia','SAU','682','966');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('188','SN','SENEGAL','Senegal','SEN','686','221');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('189','CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL,'381');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('190','SC','SEYCHELLES','Seychelles','SYC','690','248');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('191','SL','SIERRA LEONE','Sierra Leone','SLE','694','232');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('192','SG','SINGAPORE','Singapore','SGP','702','65');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('193','SK','SLOVAKIA','Slovakia','SVK','703','421');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('194','SI','SLOVENIA','Slovenia','SVN','705','386');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('195','SB','SOLOMON ISLANDS','Solomon Islands','SLB','90','677');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('196','SO','SOMALIA','Somalia','SOM','706','252');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('197','ZA','SOUTH AFRICA','South Africa','ZAF','710','27');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('198','GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL,'0');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('199','ES','SPAIN','Spain','ESP','724','34');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('200','LK','SRI LANKA','Sri Lanka','LKA','144','94');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('201','SD','SUDAN','Sudan','SDN','736','249');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('202','SR','SURINAME','Suriname','SUR','740','597');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('203','SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM','744','47');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('204','SZ','SWAZILAND','Swaziland','SWZ','748','268');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('205','SE','SWEDEN','Sweden','SWE','752','46');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('206','CH','SWITZERLAND','Switzerland','CHE','756','41');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('207','SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760','963');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('208','TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN','158','886');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('209','TJ','TAJIKISTAN','Tajikistan','TJK','762','992');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('210','TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834','255');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('211','TH','THAILAND','Thailand','THA','764','66');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('212','TL','TIMOR-LESTE','Timor-Leste',NULL,NULL,'670');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('213','TG','TOGO','Togo','TGO','768','228');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('214','TK','TOKELAU','Tokelau','TKL','772','690');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('215','TO','TONGA','Tonga','TON','776','676');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('216','TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780','1868');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('217','TN','TUNISIA','Tunisia','TUN','788','216');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('218','TR','TURKEY','Turkey','TUR','792','90');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('219','TM','TURKMENISTAN','Turkmenistan','TKM','795','7370');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('220','TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796','1649');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('221','TV','TUVALU','Tuvalu','TUV','798','688');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('222','UG','UGANDA','Uganda','UGA','800','256');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('223','UA','UKRAINE','Ukraine','UKR','804','380');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('224','AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784','971');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('225','GB','UNITED KINGDOM','United Kingdom','GBR','826','44');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('226','US','UNITED STATES','United States','USA','840','1');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('227','UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL,'1');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('228','UY','URUGUAY','Uruguay','URY','858','598');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('229','UZ','UZBEKISTAN','Uzbekistan','UZB','860','998');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('230','VU','VANUATU','Vanuatu','VUT','548','678');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('231','VE','VENEZUELA','Venezuela','VEN','862','58');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('232','VN','VIET NAM','Viet Nam','VNM','704','84');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('233','VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','92','1284');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('234','VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850','1340');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('235','WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF','876','681');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('236','EH','WESTERN SAHARA','Western Sahara','ESH','732','212');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('237','YE','YEMEN','Yemen','YEM','887','967');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('238','ZM','ZAMBIA','Zambia','ZMB','894','260');
insert into `countries` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) values('239','ZW','ZIMBABWE','Zimbabwe','ZWE','716','263');
